### ISSUE TITLE
Field 18 not set in this version of the code

### ISSUE THREAD

**Issue by ajamyajax** [KeplerGO/K2ephem#7]
Dear Geert, 

Maybe a minor issue for K2ephem with K2fov 6.3.dev0 installed?

Thanks, Mark

Traceback (most recent call last):
  File "C:\python36\lib\site-packages\K2fov\fields.py", line 55, in getFieldInfo
    info = _getCampaignDict()["c{0}".format(fieldnum)]
KeyError: 'c18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python36\lib\site-packages\K2ephem\K2ephem.py", line 142, in check_target
    ephem = get_ephemeris_dataframe(target, first, last)
  File "C:\python36\lib\site-packages\K2ephem\K2ephem.py", line 129, in get_ephemeris_dataframe
    fileobj = get_ephemeris_file(target, first, last, step_size)
  File "C:\python36\lib\site-packages\K2ephem\K2ephem.py", line 116, in get_ephemeris_file
    "stop": K2fov.getFieldInfo(last)["stop"],
  File "C:\python36\lib\site-packages\K2fov\fields.py", line 64, in getFieldInfo
    "of the code".format(fieldnum))
ValueError: Field 18 not set in this version of the code

**Comment by barentsen** [comment]
Thanks @ajamyajax.  Fields 17 and beyond are not set in stone at present.  I have just pushed a fix to master so that K2ephem only checks up to Field 16.

**Comment by ajamyajax** [comment]
Thanks, Geert!

Your fix works just fine.  Mark
